settings:
  title: '服务器运行状态监控'
  url: 'https://status-page.eidam.dev'
  logo: logo-192x192.png
  daysInHistogram: 90
  collectResponseTimes: true

  allmonitorsOperational: '所有系统正常运行'
  notAllmonitorsOperational: '所有系统未正常运行'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '未正常运行'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '全部正常'
  dayInHistogramNotOperational: '故障'

monitors:    
  - id: 1
    name: 主站
    description: ''
    url: 'https://easysys.top'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
    
  - id: 2
    name: 博客
    description: 'E博客'
    url: 'https://blog.easysys.top'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
    
  - id: 3
    name: getmyfile
    description: 'Get文章文件'
    url: 'https://getmyfile.easysys.top'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
     
  - id: 4
    name: ECDN
    description: '一个静态资源CDN'
    url: 'https://cdn.easysys.top'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
    
  - id: 5
    name: Get!
    description: 'Get文件的云盘'
    url: 'https://get.easysys.top'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: 6
    name: E图床
    description: '图床'
    url: 'https://pic.easysys.top'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
    
  - id: 7
    name: Bugdows
    description: '适合中国人的Windows'
    url: 'https://bugdows.top'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
    
  - id: 8
    name: 控制台
    description: '服务器控制台'
    url: 'https://consle.easysys.top'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
    
  - id: 8
    name: 中国深圳服务器
    description: ''
    url: '103.44.238.46	'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
