export const locations = {
  ADL: 'Adelaide',
  AKL: '奥克兰',
  ALG: 'Algiers',
  AMM: 'Amman',
  AMS: '阿姆斯特丹',
  ARI: 'Arica',
  ARN: 'Stockholm',
  ASU: 'Asunción',
  ATH: '雅典',
  ATL: '亚特兰大',
  BAH: 'Manama',
  BCN: '巴塞罗那',
  BEG: 'Belgrade',
  BEL: 'Belém',
  BEY: 'Beirut',
  BGW: 'Baghdad',
  BKK: '曼谷',
  BLR: 'Bangalore',
  BNA: 'Nashville',
  BNE: 'Brisbane',
  BNU: 'Blumenau',
  BOG: '波哥大',
  BOM: '孟买',
  BOS: '波士顿',
  BRU: 'Brussels',
  BSB: 'Brasilia',
  BUD: 'Budapest',
  BUF: '水牛城',
  BWN: 'Bandar Seri Begawan',
  CAN: '广州',
  CBR: '堪培拉',
  CCU: 'Kolkata',
  CDG: '巴黎',
  CEB: 'Cebu',
  CFC: 'Caçador',
  CGK: 'Jakarta',
  CGO: '郑州',
  CGP: 'Chittagong',
  CKG: '重庆',
  CLT: 'Charlotte',
  CMB: 'Colombo',
  CMH: 'Columbus',
  CMN: 'Casablanca',
  CNF: 'Belo Horizonte',
  CPH: 'Copenhagen',
  CPT: 'Cape Town',
  CSX: '株洲',
  CTU: '成都',
  CUR: 'Willemstad',
  CWB: 'Curitiba',
  DAC: 'Dhaka',
  DAR: 'Dar Es Salaam',
  DEL: '新德里',
  DEN: '丹佛',
  DFW: '达拉斯',
  DKR: 'Dakar',
  DME: 'Moscow',
  DMM: 'Dammam',
  DOH: 'Doha',
  DTW: '底特律',
  DUB: '都柏林',
  DUR: 'Durban',
  DUS: 'Düsseldorf',
  DXB: '迪拜',
  EDI: '爱丁堡',
  EVN: 'Yerevan',
  EWR: '纽瓦克',
  EZE: 'Buenos Aires',
  FCO: '罗马',
  FLN: 'Florianopolis',
  FOR: 'Fortaleza',
  FRA: '法兰克福',
  GIG: '里约热内卢',
  GND: 'St. George’s',
  GOT: 'Gothenburg',
  GRU: '圣保罗',
  GUA: '危地马拉',
  GVA: '日内瓦',
  GYD: '巴库',
  GYE: 'Guayaquil',
  HAM: 'Hamburg',
  HAN: '河内',
  HEL: 'Helsinki',
  HKG: '香港',
  HNL: '檀香山',
  HRE: 'Harare',
  HYD: 'Hyderabad',
  IAD: '阿什本',
  IAH: '休斯顿',
  ICN: '首尔',
  IND: 'Indianapolis',
  ISB: 'Islamabad',
  IST: 'Istanbul',
  ITJ: 'Itajaí',
  JAX: 'Jacksonville',
  JIB: 'Djibouti City',
  JNB: 'Johannesburg',
  JSR: 'Jashore',
  KBP: 'Kyiv',
  KEF: 'Reykjavík',
  KGL: 'Kigali',
  KHI: 'Karachi',
  KIV: 'Chișinău',
  KIX: 'Osaka',
  KJA: 'Krasnoyarsk',
  KTM: 'Kathmandu',
  KUL: 'Kuala Lumpur',
  KWI: 'Kuwait City',
  LAD: 'Luanda',
  LAS: 'Las Vegas',
  LAX: '洛杉矶',
  LCA: 'Nicosia',
  LED: 'Saint Petersburg',
  LHE: 'Lahore',
  LHR: 'London',
  LIM: 'Lima',
  LIS: 'Lisbon',
  LOS: 'Lagos',
  LUX: 'Luxembourg City',
  MAA: 'Chennai',
  MAD: 'Madrid',
  MAN: 'Manchester',
  MBA: 'Mombasa',
  MCI: 'Kansas City',
  MCT: 'Muscat',
  MDE: 'Medellín',
  MEL: '墨尔本',
  MEM: 'Memphis',
  MEX: 'Mexico City',
  MFE: 'McAllen',
  MFM: 'Macau ',
  MGM: 'Montgomery',
  MIA: 'Miami',
  MLE: 'Malé',
  MNL: 'Manila',
  MPM: 'Maputo',
  MRS: 'Marseille',
  MRU: 'Port Louis',
  MSP: 'Minneapolis',
  MUC: 'Munich',
  MXP: 'Milan',
  NAG: 'Nagpur',
  NBG: 'Ningbo',
  NBO: 'Nairobi',
  NOU: 'Noumea',
  NRT: 'Tokyo',
  OMA: 'Omaha',
  ORD: '芝加哥',
  ORF: 'Norfolk',
  OSL: 'Oslo',
  OTP: 'Bucharest',
  PAP: 'Port',
  PBH: 'Thimphu',
  PBM: 'Paramaribo',
  PDX: 'Portland',
  PER: 'Perth',
  PHL: '费城',
  PHX: 'Phoenix',
  PIT: 'Pittsburgh',
  PMO: 'Palermo',
  PNH: 'Phnom Penh',
  POA: 'Porto Alegre',
  PRG: 'Prague',
  PTY: 'Panama City',
  QRO: 'Queretaro',
  QWJ: 'Americana',
  RAO: 'Ribeirao Preto',
  RGN: 'Yangon',
  RIC: 'Richmond',
  RIX: 'Riga',
  ROB: 'Monrovia',
  RUH: 'Riyadh',
  RUN: 'Réunion',
  SAN: '圣迭戈',
  SCL: '圣地亚哥',
  SEA: '西雅图',
  SGN: 'Ho Chi Minh City',
  SHA: '上海',
  SIN: '新加坡',
  SJC: '圣何塞',
  SJO: '哥斯达黎加',
  SJP: '圣若泽里约普雷图',
  SKG: 'Thessaloniki',
  SLC: 'Salt Lake City',
  SMF: 'Sacramento',
  SOD: 'Sorocaba',
  SOF: 'Sofia',
  SSA: 'Salvador',
  STL: 'St. Louis',
  SVX: 'Yekaterinburg',
  SYD: 'Sydney',
  SZV: '苏州',
  TBS: 'Tbilisi',
  TGU: 'Tegucigalpa',
  TLH: 'Tallahassee',
  TLL: 'Tallinn',
  TLV: 'Tel Aviv',
  TNA: 'Jinan',
  TNR: 'Antananarivo',
  TPA: 'Tampa',
  TPE: '台北',
  TSN: '天津',
  TUN: 'Tunis',
  TXL: '柏林',
  UIO: 'Quito',
  ULN: 'Ulaanbaatar',
  URT: 'Surat Thani',
  VCP: 'Campinas',
  VIE: '维也纳',
  VNO: 'Vilnius',
  VTE: 'Vientiane',
  WAW: '华沙',
  WUH: '武汉',
  WUX: '无锡',
  XIY: '西安',
  YUL: '蒙特利尔',
  YVR: '温哥华',
  YWG: 'Winnipeg',
  YXE: 'Saskatoon',
  YYC: 'Calgary',
  YYZ: '多伦多',
  ZAG: 'Zagreb',
  ZDM: 'Ramallah ',
  ZRH: '苏黎世',
}
